### ISSUE TITLE
How would one go about wrapping a function with pointer as a parameter?

### ISSUE THREAD

**Issue by kehrazy** [idlesign/ctyped#1]
amazing work on this library, it's been great using it so far.

i have a question.

say, i have a function in a library:
```c
void foo(int flag, int* i) {
    *i = flag;
}
```

and, in python, i would've done something along the lines of:
```python
def foo(flag):
   argtypes = [ct.c_int, ct.pointer(ct.c_int)] # i declare the calling signature
   args = (flag, ct.pointer(ct.c_int(to_ret))) # i make the arguments
   call_function(args=args, argtypes=argtypes) # i call the function
```

but, with the library, i can't seem to call the functions of such form?

will be looking to your response, sorry for necrobumping this.

ty.

**Comment by idlesign** [comment]
Thank you.

Looks somewhat similar to 
https://github.com/idlesign/ctyped/blob/master/tests/test_basic.py#L145
https://github.com/idlesign/ctyped/blob/master/tests/mylib/mylib.c#L63

Please take a look at it and let me know whether it budges.

**Comment by kehrazy** [comment]
yep, that's what I've been looking for. seems to work now, tysm.
